SignalK/nmea0183-signalk

codecs/MWV.js, codecs/VHW.js, lib/NMEA0183.js, package.json, test/issue17.js
* Add parsing for the VHW (Water Speed and Heading) statement
* Fix incorrect units in the parser for MWV (Wind speed & direction)
* Fix and improve tests for the VHW and MWV statements.
=> Add parser for VHW, correct MWV, improve tests

lib/index.js, test/issue14.js
@tkurki 
What do you think of this fix for the issue? It's as basic as it gets, but should do the job. I'm a bit unsure I'm not forgetting anything, because this seems too easy...
=> possible fix for #14

codecs/DBT.js, codecs/MWV.js, test/DBT.js, test/MWV.js, test/parsing.js
Fix for #24 started. Not yet ready for merging.
=> Deep paths fix

codecs/MWV.js, test/MWV.js
If the validity field is empty the message is discarded.
With my data set this was the only problematic case and I would like to get this to master asap.
Closes #29
=> Fix MWV handling of empty fields

codecs/APB.js, codecs/HDM.js, codecs/HDT.js, codecs/MWV.js, codecs/RMC.js, codecs/VDM.js, codecs/VHW.js, codecs/VTG.js, lib/NMEA0183.js, package.json, test/parsing.js
Note: something is wrong with the test suite -- causing a memory allocation error. The problem wasn't introduced with these changes, @tkurki reproduced them on master. Seems to be caused by a dependency.
=> Updated units to SI units

codecs/APB.js, codecs/DBT.js, codecs/GGA.js, codecs/GLL.js, codecs/HDM.js, codecs/HDT.js, codecs/MWV.js, codecs/RMC.js, codecs/VDM.js, codecs/VHW.js, codecs/VTG.js, lib/NMEA0183.js, test/parsing.js
This PR fixes #40 and #37. @tkurki would you mind to give it a quick look - I'd like to merge asap.
=> Fix for #40 and #37

codecs/VDR.js, codecs/index.js, test/VDR.js
Fixed schema from previous PR
new file:   codecs/VDR.js
modified:   codecs/index.js
new file:   test/VDR.js
=> Added support for VDR (current set and drift)

codecs/VWR.js, codecs/index.js, test/VWR.js
=> Added support for (deprecated) VWR sentence

README.md
Addresses issue #20 ... more or less.
=> Add Some Useful Info To README.md

codecs/ROT.js
Spec says rad/s, NMEA outputs deg/min
=> Changed ROT from deg/min to rad/s

hooks/HDG.js, test/DBT.js, test/HDG.js
Added HDG with test and a test for value of DBT
=> Added HDG hook

hooks/RMB.js, test/RMB.js
Add support for (RMB)[http://www.catb.org/gpsd/NMEA.html#_rmb_recommended_minimum_navigation_information] sentences. as promised in issue #81  ! 
Tested mainly with the unit tests... I was not able to use the development branch with the server. Is there an equivalent branch on the server i should use to match the dev branch ?
=> Rmb support

codecs/ZDA.js, codecs/index.js, lib/NMEA0183.js, test/ZDA.js
- Add support for ZDA sentence to produce `navigation.datetime`
- Fix timestamps with with years from 2000-2010
=> ZDA sentence

lib/index.js, test/GLL.js
=> fix: catch errors from decode

hooks/HDG.js, test/HDG.js
The new parser is not working with HDG with just the heading field, which my equipment happens to produce.
=> fix: HDG with just heading

package.json, test/RMC.js
The timestamp function in nmea0183-utilities has the issue
=> seconds are missing

README.md, hooks/VLW.js, package-lock.json, test/VLW.js
Parse VLW nmea sentences.  Total cumulative distance posted to
navigation.log.  Distance since reset posted to navigation.trip.log
=> feature: Parse VLW

package-lock.json, package.json
=> [WIP] fix(package): update ggencoder and moment-timezone

README.md
It will help debugging to mention that unknown sentences are silently discarded.
=> doc: add note on unknown sentence treatment.

hooks/VDM.js, test/VDM.js
=> fix: AIS status  'motoring' does not convert

hooks/VDM.js, test/VDM.js
=> feature: add support for imo to VDM

hooks/VDM.js, test/VDM.js
=> [WIP] fix: add missing 'default' nav state for VDM

hooks/VDM.js, package.json, test/VDM.js
=> feature: add support for aton virtual flag

hooks/VDM.js, test/VDM.js
=> feature: support aton off position indicator

hooks/BOD.js, hooks/BWC.js, hooks/BWR.js, hooks/HSC.js, hooks/XTE.js
Tiny typo errors corrections on 5 hooks files
=> Tiny typo errors corrections 

hooks/DBK.js, hooks/DBS.js, hooks/DBT.js, hooks/DPT.js, test/DBK.js, test/DBS.js, test/DBT.js, test/DPT.js
=> [WIP] fix: output null when depth not available

hooks/seatalk/0x54.js
See https://github.com/SignalK/set-system-time/issues/12.
=> fix: seatalk 0x54 month off by one
