codecs/GLL.js, test/GLL.js
GLL conversion output was not valid Signal K because of the missing label property, probably due to the fact position value is an object.
=> Fix missing label in GLL conversion by outputting delta directly from codec

lib/index.js
The proprietary sentences will keep the 4 character talker id as "instrument", including "P". This can later be used to distinguish between different protocols with the same "type"
=> Added provision for proprietary sentences

codecs/VDM.js, test/VDM.js
Add support for multiline AIS messages.
Improves AIS message handling a bit, so that it checks for existence of individual fields and creates delta accordingly.
The session handling is naive and **will not work for multiple ais streams** because of a shared singleton. The parser needs more changes to support a per parser instance session context.
=> Multiline ais

README.md, codecs/DSC.js, codecs/index.js, test/DSC.js
This codec currently contains basic support for distress messages and
position messages.
NOTE: The position in the DSC sentence is only accurate to the minute,
however, there is an extended sentence that provides further detail. The
DSE Sentence (which can follow the DSC sentence) contains further position
detail.
```
elektron@x61s-44a5:~/code/signalk-parser-nmea0183$ npm test test/DSC.js
> nmea0183-signalk@0.2.4 test /home/elektron/code/signalk-parser-nmea0183
> mocha "test/DSC.js"
DSC Position
✓ converts ok (512ms)
DSC Distress
✓ converts ok
2 passing (599ms)
```
=> Add Basic support for DSC Position and Distress Sentences

codecs/STALK.js, codecs/index.js, lib/index.js, test/STALK.js
Seatalk1 units should be able to speak NMEA, or at least there are translators available from seatalk1 to NMEA0183, but for more fine grained information, there are some pieces of the puzzle that are not available in NMEA0183. Some units like this one http://www.gadgetpool.de/bestellen/catalog/product_info.php/products_id/54
provide seatalk1 datagrams enclosed in a $STALK sentence. This is an attempt of getting seatalk info from $STALK into SignalK. Now the procedure could be different, and I hope you have some specific input (architecture etc). The STALK.js file may become cumbersomely large if this expands, so it may be necessary to split the different datagram decoders into separate files, but I have not managed to do so. 
The only datagram that has been populated is 0x84, but this …
=> Support for Seatalk through $STALK sentence

codecs/VDM.js, lib/index.js, test/VDM.js
Ais session has been a singleton, which will mess things up
if you run several Parsers concurrently and they have ais data.
The session is monkeypatched to multiplexer, which is the only
available context in consecutive invocations.
Fixes #78.
=> Fix #78: de-singleton ais session

README.md
Script returns SignalK sparse (or full) data. Not in the "update" format.
=> Fix return type in README

lib/NMEA0183.js
Month for January is 0 not 1. So it was one month to high.
=> correct timestamp RMC

lib/index.js
When an application or user executes the `Parser#parse(sentence)` method, the method checks if the sentence is a non-empty string and emits a `nmea0183` event with that sentence.
=> Emit "nmea0183" event before a sentence is parsed

bin/nmea0183-signalk
Instead output the delta directly like the n2k-parser program does.
This fixes #104.
=> Do not include a key named 'delta' with delta data in output

lib/findHook.js, lib/parse.js
Require the hooks once upon startup, foregoing the synchronous
file system access for each sentence.
=> refactor: more efficient findHook

hooks/VWR.js, lib/parse.js, test/VWR.js
Example sentence:  $IIVWR,024,L,018,N,,,,*5e   should be accepted (w/ 4 missing values)
var 'empty' not > 4 then continue / set environment.wind values.
=> Fix: VWR, ok if 4 empty fields (eg. fields 4-7)

README.md, hooks/MDA.js, hooks/index.js, test/MDA.js
Adds support for NMEA 0183 MDA sentence type, containing meteorological composite.
This message type is used by Thies Clima, and probably other major instrument makers.
Changes to be committed:
modified:   README.md
new file:   hooks/MDA.js
modified:   hooks/index.js
new file:   test/MDA.js
=> Adds support for NMEA 0183 MDA sentence type

hooks/APB.js, hooks/BOD.js, hooks/BWC.js, hooks/BWR.js, hooks/HSC.js, hooks/XTE.js, hooks/index.js, lib/index.js, package.json, test/APB.js, test/BOD.js, test/BWC.js, test/BWR.js, test/HSC.js, test/XTE.js
This PR implements hooks & tests for the following NMEA0183 sentences:
1. ABP - Autopilot sentence "B"*
2. BOD - Bearing origin to destination waypoint
3. BWC - Bearing and distance to waypoint - great circle
4. BWR - Bearing and distance to waypoint - rhumb line
5. HSC - Heading steering command
6. XTE - Cross-track error
_* There used to be a hook for APB, but it had been deprecated in the past due to spec changes_
=> Implement hooks for various sentences related to autopilot operation

hooks/proprietary/PBVE.js, test/PBVE.js, test/PNKEP.js
Added product code E, engine coolant temperature
Added the following meta for providing CruzPro gauge information:
- Backlight level
- Gauge units
- High alarm value, included in zones with messaging
- Low alarm value, included in zones with messaging
- Gauge alarm armed
- Original value for debugging
Added conversion into signalk specified format (f->k, psi->pa)
Updated unit tests to verify all meta model values
Verified with @sk/instrumentPanel and CruzPro gauges (see attached photos)
Note: Temperature is off one degree due to latency between photo and screenshot. Numbers are identical in realtime.
=> feature: PBVE -  auxillary engine temperature

hooks/VDM.js, package.json, test/VDM.js
=> feature: add ais class

hooks/VDM.js, test/VDM.js
smi is under the path `navigation.specialManeuver` and can be `not available`, `not engaged`, `engaged` or `reserved`
`sensors.ais.designatedAreaCode` and `sensors.ais.functionalId` are integers
Closes #165
=> feature: add information needed to detect bluesign

README.md, hooks/MTA.js, hooks/MWD.js, hooks/VWT.js, hooks/index.js, test/MTA.js, test/MWD.js, test/VWT.js
Hi,
integrated a NKE instrument system with SignalK. 
Added the following sentences (all sent by the NKE Multigraphic) to the NMEA parser:
- MTA, mean temperature of air
- MWD, wind speed and direction
- VWT, true wind angle and speed
Thanks for all your great work with SignalK!
=> feature: add MTA,  MWD  and VWT sentences

.gitignore, README.md, bin/nmea0183-signalk, custom-sentence-plugin/index.js, custom-sentence-plugin/package.json, lib/index.js, lib/transformSource.js, test/customSentenceParser.js
This PR adds a mechanism how a SK Server plugin can publish new sentence parsers, that the server passes to the NMEA0183 parser. See the included example of such a plugin for details.
todo:
=> Custom sentence parser mechanism

hooks/GGA.js
It's rather normal the GGA message has four empty last fields so the "if (empty > 3) {
return null" will normally "kick" out GGA.
=> GGA: Correct empty fields count. The four last are normally empty

hooks/RMB.js, test/RMB.js
XTE.js has this
const direction = parts[3].trim().toUpperCase() === 'L' ? 1 : -1
signalk-to-nmea0183/sentences/RMB.js has this
return nmea.toSentence([
'$IIRMB',
crossTrackError.toFixed(2),
crossTrackError < 0 ? 'R' : 'L',
...
RMB.js does the opposite, and produces a negative value when the required
correction is to steer left. The definition in XTE.js appears to produce the
expected result in combination with my autopiot and the NMEA2000 conversions
as well, so let's change RMB.js to match XTE.js
Signed-off-by: Ard Biesheuvel <ardb@kernel.org>
=> Fix sign of cross track error obtained from RMB sentence

hooks/GGA.js, test/GGA.js
When horizontalDilution was < 1.0 it was being set to zero causing troubles.  3 other values (MSL Altitude ,Geoid Separation, & Age of differential GPS data) were being set to int when the GGA sentence accepts float.
=> change four values from int to float to match GGA sentence

lib/index.js, test/RMB.js
The contract of nmea0183-signalk should be to convert
source data to Signal K and only source data. If it
fills in timestamp downstream processing can not distinguish
between timestamp from source data and timestamp filled
in on the fly with current time.
Fixes #222.
=> feature: do not fill timestamp

hooks/VTG.js, test/VTG.js
FIxes #226.
Also changes conversion to use km/h for speed conversion if there is a >0 value for it. Previously that value would get converted but not used as it was overwritten with the value converted from knots.
=> fix: output null for missing COG in VTG, prefer km/h for speed

hooks/proprietary/PBVE.js
http://www.cruzpro.com/rh60.html
Decoding from https://www.electronicspoint.com/forums/threads/engine-hour-meter-with-nmea-output.159207/
=> Added support for RPM and Engine Runtime from Cruzpro RH30/60/110 - Productcode B

hooks/HDG.js, test/HDG.js
Fixes #235.
Previously deviation was not handled at all. Now if there is deviation it is applied to create nav.headingMagnetic and in addition nav.headingCompass is output. This PR also adds deviation to the output.
If there is no deviation value the output is as previously: the sensor value in the first field is output as is as nav.headingMagnetic and no nav.headingCompass. This is a bit backwards, as what is being output is nav.headingCompass, but I think changing that would warrant a major version change for being so incompatible with the current behavior.
If the sentence includes variation also nav.headingTrue is output.
=> fix: HDG deviation handling

hooks/proprietary/PSMDST.js, test/seatalk.js
The ShipModul Miniplex has added a field to the PSMDST message to indicate sending to 'C' or receiving from 'R' the SeaTalk network. This change adds support for the new field by looking for the 'R' field then parsing the data accordingly.
=> Added support for ShipModul Miniplex Latest Firmware

hooks/seatalk/0x25.js, test/seatalk.js
Fix the formula for calculating ST 0x25 datagram total log.
These are equivalent:
```
- >> 4 and multiply by 65536
- zero out the 8 least significant bits and multiply by 4096
```
but not both >>4 and multiply by 4096 that it was doing.
Fixes #248.
=> fix: ST 0x25 log calculation

hooks/RMB.js, test/RMB.js
The RMB parser stored the next waypoint position to navigation.courseRhumbline.nextPoint
This is incorrect, and is changed to navigation.courseRhumbline.nextPoint.position
Fixes #240.
=> Update RMB.js - Address issue #240

hooks/VDM.js, test/VDM.js
**Issue:** (#253)
`salinity` and `relativeHumidity` paths in the specification (`environment` group) are defined with the unit `ratio`.
Values from the VDM sentence are written to these signal K paths as a number representing a percentage (e.g. 80) rather than a ratio (i.e. 0.8).
This PR converts the received values to a ratio so they align with the specification.
=> Fix: convert salinity and relativeHumidity  in VDM from percentage values to ratio

hooks/BWC.js, hooks/BWR.js, hooks/RMB.js, test/BWC.js, test/BWR.js, test/RMB.js
Fix RMB, BWC and BWR sentence processing behaviour to send a delta when position field values are missing.
**_Current behaviour:_**
Whe position field values are missing, function does not return data and no delta is sent.
This means that clients are left unaware of a previously active destination being "de-activated" and will continue to show the destination as active.
**_FIx:_**
When position field values are missing, return data so that a delta is sent with `nextPoint.position` value = null.
=> Fix: not sending delta when next position values are missing

hooks/MTA.js, hooks/MTW.js, test/MTA.js, test/MTW.js
Empty values like in '$RAMTW,,C*1E' are now converted to 0 degrees Celsius (or 273.15K). 
This is incorrect and also not in line with similar cases in for depth data (DPT, DBK).
=> fix: output null for empty MTA (air) or MTW (water) temperature.
